config/routes.rb
# == Route Map
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#                     start GET    /start(.:format)                                                                         records#create
#                      stop GET    /stop(.:format)                                                                          records#update
#                   records GET    /records(.:format)                                                                       records#show
#                      line POST   /line(.:format)                                                                          records#line_notify_send
#                     login GET    /login(.:format)                                                                         sessions#new
#                           POST   /login(.:format)                                                                         sessions#create
#                    logout GET    /logout(.:format)                                                                        sessions#destroy
#                    signup GET    /signup(.:format)                                                                        users#new
#                           POST   /signup(.:format)                                                                        users#create
#                     about GET    /about(.:format)                                                                         static_pages#about
#                      help GET    /help(.:format)                                                                          static_pages#help
#                   contact GET    /contact(.:format)                                                                       static_pages#contact
#                     users GET    /users(.:format)                                                                         users#index
#                           POST   /users(.:format)                                                                         users#create
#                  new_user GET    /users/new(.:format)                                                                     users#new
#                 edit_user GET    /users/:id/edit(.:format)                                                                users#edit
#                      user GET    /users/:id(.:format)                                                                     users#show
#                           PATCH  /users/:id(.:format)                                                                     users#update
#                           PUT    /users/:id(.:format)                                                                     users#update
#                           DELETE /users/:id(.:format)                                                                     users#destroy
#                      root GET    /                                                                                        records#new
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  get '/start', to: 'records#create'
  get '/stop', to: 'records#update'
  get '/records', to: 'records#show'
  post '/line', to: 'records#line_notify_send'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/about', to: 'static_pages#about'
  get '/help', to: 'static_pages#help'
  get '/contact', to: 'static_pages#contact'
  resources :users
  root to: 'records#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_btn.html.slim
- if @user_records.last
  - if @user_records.last[:stop_time]
    h1 Here we go!!
    = link_to 'START', start_path, class: 'btn btn-primary btn-lg'
    h2 Send to your record for your Line account.
    = link_to 'Send to Line', line_path, method: :post, class: 'btn btn-success btn-lg'
    p.mt-3  Your last learning is
    p.mt-3  = @user_records.last[:updated_at].strftime('%Y/%m/%d %T')
    = render 'layouts/chart'
  - else
    h1 Click to stop-button is just stop learning.
    = link_to 'STOP', stop_path, id: 'stopBtn', class: 'btn btn-danger btn-lg mr-1'
    h3 If you want to add emotion, then click byn below.
    = link_to '1', stop_path(emotion: 1), class: 'btn btn-danger btn-lg mr-1'
    = link_to '2', stop_path(emotion: 2), class: 'btn btn-warning btn-lg mr-1'
    = link_to '3', stop_path(emotion: 3), class: 'btn btn-info btn-lg mr-1'
    = link_to '4', stop_path(emotion: 4), class: 'btn btn-primary btn-lg'
    = render 'layouts/dialog'
    #area_time
    = render 'layouts/timer'  
- else
  h1 Let's Start Learning!!
  = link_to 'START', start_path, class: 'btn btn-primary btn-lg'

app/views/layouts/_chart.html.slim
canvas#chartTimes width="400" height="400"
javascript:
  var ctx = document.getElementById('chartTimes').getContext('2d');
  var myChart = new Chart(ctx, {
      type: 'bar',
      data: {
          labels: [
              moment(new Date(gon.created_time_at_the_6th_to_last)).format("MM/DD hh:DD"),
              moment(new Date(gon.created_time_at_the_5th_to_last)).format("MM/DD hh:DD"),
              moment(new Date(gon.created_time_at_the_4th_to_last)).format("MM/DD hh:DD"),
              moment(new Date(gon.created_time_at_the_3rd_to_last)).format("MM/DD hh:DD"),
              moment(new Date(gon.created_time_at_the_2nd_to_last)).format("MM/DD hh:DD"),
              moment(new Date(gon.created_time_at_the_1st_to_last)).format("MM/DD hh:DD")
                ],
          datasets: [{
              label: '# of Votes',
              data: [
              gon.learning_time_at_the_6th_to_last,
              gon.learning_time_at_the_5th_to_last,
              gon.learning_time_at_the_4th_to_last,
              gon.learning_time_at_the_3rd_to_last,
              gon.learning_time_at_the_2nd_to_last,
              gon.learning_time_at_the_1st_to_last
              ],
              backgroundColor: [
                  'rgba(255, 99, 132, 1.0)',
                  'rgba(54, 162, 235, 1.0)',
                  'rgba(255, 206, 86, 1.0)',
                  'rgba(75, 192, 192, 1.0)',
                  'rgba(153, 102, 255, 1.0)',
                  'rgba(255, 159, 64, 1.0)'
              ],
              borderColor: [
                  'rgba(255, 99, 132, 1)',
                  'rgba(54, 162, 235, 1)',
                  'rgba(255, 206, 86, 1)',
                  'rgba(75, 192, 192, 1)',
                  'rgba(153, 102, 255, 1)',
                  'rgba(255, 159, 64, 1)'
              ],
              borderWidth: 1
          }]
      },
      options: {
          scales: {
              yAxes: [{
                  ticks: {
                      beginAtZero: true
                  }
              }]
          }
      }
  });

app/views/layouts/_debug.html.slim
- if Rails.env.development?
  .container.bg-light.text-dark
    h1 【開発環境用 デバッグ情報】
    .row
      .col-6
        h2 【params】
        = debug(params)
      .col-6
        h2 【flash】
        = debug(flash)
    .row
      .col-6
        h2 【@current_user】
        = debug(@current_user)
      .col-6
        h2 【Record.last】
        = debug(Record.last)
    .row
      .col-4
        h2 【@user】
        = debug(@user)
    .row
      .col-6
        h2 【user】
      .col-6
        h2 【current_user】
        = debug(current_user)

app/views/layouts/_dialog.html.slim
/= link_to 'おためし', root_path, data: { confirm: "本当に「あめち」を削除してよろしいですか？", verify: "", verify_text: "削除する場合は商品名を入力してください", cancel: "やめる", commit: "削除する" }, title: "削除の確認", class: "btn btn-secondary btn-lg ml-5"

app/views/layouts/_footer.html.slim
footer.footer
  .navbar.navbar-expand-sm.navbar-dark.darken-bg-color
    ul.navbar-nav.mr-auto
      li.nav-item
        p copyright terufumi all rights reserve.
    ul.navbar-nav
      li.nav-item
        = link_to 'About', about_path, class: 'nav-link'
      li.nav-item
        = link_to 'Contact', contact_path, class: 'nav-link'

app/views/layouts/_form.html.slim
= form_with model: @user, local: true do |f|
  .form-group.d-flex.flex-column
    = f.label :name
    = f.text_field :name, class: 'form-controll'
  .form-group.d-flex.flex-column
    = f.label :email
    = f.email_field :email, class: 'form-controll'
  .form-group.d-flex.flex-column
    = f.label :password
    = f.password_field :password, class: 'form-controll'
  .form-group.d-flex.flex-column
    = f.label 'Confirm'
    = f.password_field :password_confirmation, class: 'form-controll'
  = f.submit 'Submit', class: 'btn btn-warning'

app/views/layouts/_header.html.slim
header.header
  .navbar.navbar-expand-sm.navbar-light.lighten-bg-color
    ul.navbar-nav.mr-auto
      li.nav-item
        = link_to 'Learning Time', root_path, class: 'navbar-brand'
    ul.navbar-nav
      li.nav-item
        = link_to 'About', about_path, class: 'nav-link'
      li.nav-item
        = link_to 'Contact', contact_path, class: 'nav-link'
      li.nav-item
        = link_to 'Help', help_path, class: 'nav-link'
      - if @current_user
        li.nav-item
          = link_to 'Records', records_path, class: 'nav-link'
        li.nav-item
          = link_to 'Profile', user_path(@current_user), class: 'nav-link'
        li.nav-item
          = link_to 'Settings', '#', class: 'nav-link'
        li.nav-item
          = link_to 'Log out', logout_path, class: 'nav-link'
      - else
        li.nav-item
          = link_to 'Log in', login_path, class: 'nav-link'

app/views/layouts/_profile.html.slim
- if @current_user
  h2 profile
  h4 Name
  p = @current_user.name

- else
  h2 Let's Signup or Log in!!

app/views/layouts/_timer.html.slim
#output class='elapsed-time'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = full_title(yield(:title))
    = include_gon
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"
    script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment.js"
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body.main-bg-color.main-font-color
    = render 'layouts/header'
    = render 'shared/flash'
    = yield
    = render 'layouts/footer'
    = render 'layouts/debug'